name: clojure

on:
  push:
    paths:
      - clojure/language.yaml
      - .github/workflows/clojure.yml

jobs:
  BuildDevcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Devcontainer
        run: bash generate.sh clojure --test
