name: clojure

on:
  push:
    paths:
      - clojure/language.yaml
      - .github/workflows/clojure.yml

jobs:
  BuildDevcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Devcontainer
        run: bash generate.sh clojure

      - name: Build Devcontainer
        run: |
          npm install -g @devcontainers/cli
          devcontainer build --workspace-folder clojure --image-name clojure-devcontainer

      - name: Run Selftest
        run: docker run --rm clojure-devcontainer sh /selftest.sh
