name: elm

on:
  push:
    paths:
      - elm/language.yaml
      - elm/.devcontainer/**
      - .github/workflows/elm.yml
      - .templates/**

jobs:
  BuildDevcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Devcontainer
        run: bash generate.sh elm

      - name: Build Devcontainer
        run: |
          npm install -g @devcontainers/cli
          devcontainer build --workspace-folder elm --image-name elm-devcontainer

      - name: Show Disclaimer
        run: docker run --rm elm-devcontainer sh /disclaimer.sh

      - name: Run Selftest
        run: docker run --rm elm-devcontainer sh /selftest.sh
