name: elm

on:
  push:
    paths:
      - elm/language.yaml
      - .github/workflows/elm.yml

jobs:
  BuildDevcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Devcontainer
        run: bash generate.sh elm --test
