name: erlang

on:
  push:
    paths:
      - erlang/language.yaml
      - erlang/.devcontainer/**
      - .github/workflows/erlang.yml
      - .templates/**

jobs:
  BuildDevcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Devcontainer
        run: bash generate.sh erlang

      - name: Build Devcontainer
        run: |
          npm install -g @devcontainers/cli
          devcontainer build --workspace-folder erlang --image-name erlang-devcontainer

      - name: Run Selftest
        run: docker run --rm erlang-devcontainer sh /selftest.sh
