name: erlang

on:
  push:
    paths:
      - erlang/.devcontainer/**
      - .github/workflows/erlang.yml

jobs:
  CancelPrevious:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Old Pipeline
        uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  BuildDevcontainer:
    needs: [CancelPrevious]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Devcontainer
        run: |
          npm install -g @devcontainers/cli
          devcontainer build --workspace-folder erlang --image-name erlang-devcontainer

      - name: Show Disclaimer
        run: docker run --rm erlang-devcontainer sh /disclaimer.sh

      - name: Run Selftest
        run: docker run --rm erlang-devcontainer sh /selftest.sh
