name: factor

on:
  push:
    paths:
      - factor/language.yaml
      - .github/workflows/factor.yml

jobs:
  BuildDevcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Devcontainer
        run: bash generate.sh factor

      - name: Build Devcontainer
        run: |
          npm install -g @devcontainers/cli
          devcontainer build --workspace-folder factor --image-name factor-devcontainer

      - name: Run Selftest
        run: docker run --rm factor-devcontainer sh /selftest.sh
