name: factor

on:
  push:
    paths:
      - factor/language.yaml
      - .github/workflows/factor.yml

jobs:
  BuildDevcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Devcontainer
        run: bash generate.sh factor --test
