name: haskell

on:
  push:
    paths:
      - haskell/language.yaml
      - haskell/.devcontainer/**
      - .github/workflows/haskell.yml
      - .templates/**

jobs:
  BuildDevcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Devcontainer
        run: bash generate.sh haskell

      - name: Build Devcontainer
        run: |
          npm install -g @devcontainers/cli
          devcontainer build --workspace-folder haskell --image-name haskell-devcontainer

      - name: Show Disclaimer
        run: docker run --rm haskell-devcontainer sh /disclaimer.sh

      - name: Run Selftest
        run: docker run --rm haskell-devcontainer sh /selftest.sh
