name: io

on:
  push:
    paths:
      - io/language.yaml
      - .github/workflows/io.yml

jobs:
  BuildDevcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Devcontainer
        run: bash generate.sh io

      - name: Build Devcontainer
        run: |
          npm install -g @devcontainers/cli
          devcontainer build --workspace-folder io --image-name io-devcontainer

      - name: Run Selftest
        run: docker run --rm io-devcontainer sh /selftest.sh
