name: io

on:
  push:
    paths:
      - io/language.yaml
      - .github/workflows/io.yml

jobs:
  BuildDevcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: install @devcontainers/cli
        run: npm install -g @devcontainers/cli

      - name: Test Devcontainer
        run: bash generate.sh io --test
