name: io

on:
  push:
    paths:
      - io/language.yaml
      - .github/workflows/io.yml

jobs:
  BuildDevcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Devcontainer
        run: bash generate.sh io --test
