name: julia

on:
  push:
    paths:
      - julia/language.yaml
      - .github/workflows/julia.yml

jobs:
  BuildDevcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Devcontainer
        run: bash generate.sh julia --test
