name: lua

on:
  push:
    paths:
      - lua/language.yaml
      - lua/.devcontainer/**
      - .github/workflows/lua.yml
      - .templates/**

jobs:
  BuildDevcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Devcontainer
        run: bash generate.sh lua

      - name: Build Devcontainer
        run: |
          npm install -g @devcontainers/cli
          devcontainer build --workspace-folder lua --image-name lua-devcontainer

      - name: Show Disclaimer
        run: docker run --rm lua-devcontainer sh /disclaimer.sh

      - name: Run Selftest
        run: docker run --rm lua-devcontainer sh /selftest.sh
