name: prolog

on:
  push:
    paths:
      - prolog/language.yaml
      - .github/workflows/prolog.yml

jobs:
  BuildDevcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Devcontainer
        run: bash generate.sh prolog --test
