name: prolog

on:
  push:
    paths:
      - prolog/language.yaml
      - .github/workflows/prolog.yml

jobs:
  BuildDevcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Devcontainer
        run: bash generate.sh prolog

      - name: Build Devcontainer
        run: |
          npm install -g @devcontainers/cli
          devcontainer build --workspace-folder prolog --image-name prolog-devcontainer

      - name: Run Selftest
        run: docker run --rm prolog-devcontainer sh /selftest.sh
