name: ruby

on:
  push:
    paths:
      - ruby/.devcontainer/**
      - .github/workflows/ruby.yml

jobs:
  BuildDevcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Devcontainer
        run: |
          npm install -g @devcontainers/cli
          devcontainer build --workspace-folder ruby --image-name ruby-devcontainer

      - name: Show Disclaimer
        run: docker run --rm ruby-devcontainer sh /disclaimer.sh

      - name: Run Selftest
        run: docker run --rm ruby-devcontainer sh /selftest.sh
