name: ruby

on:
  push:
    paths:
      - ruby/language.yaml
      - .github/workflows/ruby.yml

jobs:
  BuildDevcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Devcontainer
        run: bash generate.sh ruby --test
