name: scala

on:
  push:
    paths:
      - scala/.devcontainer/**
      - .github/workflows/scala.yml

jobs:
  BuildDevcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Devcontainer
        run: |
          npm install -g @devcontainers/cli
          devcontainer build --workspace-folder scala --image-name scala-devcontainer

      - name: Show Disclaimer
        run: docker run --rm scala-devcontainer sh /disclaimer.sh

      - name: Run Selftest
        run: docker run --rm scala-devcontainer sh /selftest.sh
