name: scala

on:
  push:
    paths:
      - scala/language.yaml
      - .github/workflows/scala.yml

jobs:
  BuildDevcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Devcontainer
        run: bash generate.sh scala --test
