name: scala

on:
  push:
    paths:
      - scala/language.yaml
      - scala/.devcontainer/**
      - .github/workflows/scala.yml
      - .templates/**

jobs:
  BuildDevcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Devcontainer
        run: bash generate.sh scala

      - name: Build Devcontainer
        run: |
          npm install -g @devcontainers/cli
          devcontainer build --workspace-folder scala --image-name scala-devcontainer

      - name: Run Selftest
        run: docker run --rm scala-devcontainer sh /selftest.sh
